---
# tasks file for adrianjuhl.shell_capture_stdout_and_stderr

- name: "Setting facts"
  ansible.builtin.set_fact:
    role_var_name_prefix:
      "adrianjuhl__shell_capture_stdout_and_stderr__"

- name: "Setting facts"
  ansible.builtin.set_fact:
    adrianjuhl__shell_capture_stdout_and_stderr__install_dir:
      "{{ lookup('vars', role_var_name_prefix + 'install_bin_dir') }}/{{ lookup('vars', role_var_name_prefix + 'script_name') }}.d/{{ lookup('vars', role_var_name_prefix + 'version') }}"
    adrianjuhl__shell_capture_stdout_and_stderr__script_file_path:
      "{{ lookup('vars', role_var_name_prefix + 'install_bin_dir') }}/{{ lookup('vars', role_var_name_prefix + 'script_name') }}.d/{{ lookup('vars', role_var_name_prefix + 'version') }}/{{ lookup('vars', role_var_name_prefix + 'script_name') }}.sh"
    adrianjuhl__shell_capture_stdout_and_stderr__script_source_url:
      "https://raw.githubusercontent.com/adrianjuhl/adrianjuhl-shell-capture-stdout-and-stderr/refs/{{ lookup('vars', role_var_name_prefix + 'ref_type') }}/{{ lookup('vars', role_var_name_prefix + 'version') }}/bin/capture_stdout_and_stderr.sh"

- name: "Create script install directory"
  ansible.builtin.file:
    dest: "{{ adrianjuhl__shell_capture_stdout_and_stderr__install_dir }}"
    state: "directory"
    mode: "0755"

- name: "Copy script into place"
  ansible.builtin.get_url:
    url: "{{ adrianjuhl__shell_capture_stdout_and_stderr__script_source_url }}"
    dest: "{{ adrianjuhl__shell_capture_stdout_and_stderr__script_file_path }}"
    mode: "0755"
  ignore_errors: "{{ ansible_check_mode }}"
